### ISSUE TITLE
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00000002db0428>

### ISSUE THREAD

**Issue by youssefmys** [learn-co-curriculum/rails-url-helpers-lab#18]
from this [stake-overflow](https://stackoverflow.com/questions/35893584/nomethoderror-undefined-method-last-comment-after-upgrading-to-rake-11) post the error raised when using rake version higher than 11 so I think Gemfile should include `gem 'rake', '< 11.0'`  then bundler should be updated  `bundle update rake` then `bundle install`

**Comment by kingrippy** [comment]
I'm currently trying to trouble shoot this problem in my windows 10 environment. I currently have ruby and rspec installed on my macbook and everything works fine there, It seems like windows and ruby may have compatibility issues.
