### ISSUE TITLE
Suggestion for "activate page" clarity

### ISSUE THREAD

**Issue by raiet13** [learn-co-curriculum/rails-url-helpers-lab#22]
Issue : Confusion due to spec/recent labs+readings

Reasoning : The spec uses "Activate page" alongside the index and show pages, which makes it seem like the "activate page" is an actual html.erb view (as those views are what has been discussed in all of the recent labs/readings).

Suggestion : Make it clearer that the "activate page" is actually just the "activate route" and not an actual view.

**Comment by brunogarciagonzalez** [comment]
Ditto above, has been brought up to me that this lab is confusing and thus frustrating.
