### ISSUE TITLE
A small edit to the README is needed

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/rails-url-helpers-lab#25]
I am guessing that this lab has been updated recently. The README needs to be ever-so-slightly updated.

It says that "four tests are currently passing". However, when I first ran `learn` on this lab, only TWO tests were passing: "Student can be created" and "Student has a to_s instance method".

As far as I can tell right now, that's the only thing that needs to be fixed. Thanks for looking into this!

**Update:** I just fixed this in a pull request.

---Sdcrouse

**Comment by rrcobb** [comment]
Closed by #26
