### ISSUE TITLE
The "activate page" part needs to be modified or removed

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/rails-url-helpers-lab#27]
Hi. I got a little stuck when going through this lab.

When I got to the "activate page" part, it became clear that I needed to redirect to the '/students/:id' route after toggling the student's "active" status on or off. There was just one problem: none of the lessons up to this point have covered how to redirect with Rails (unless that was introduced in the Video Review near the start of the Rails module). I was able to figure it out after some research, thankfully.

I'm not sure whether the "activate page" part should be modified or removed altogether. I'm guessing that its purpose was to have us practice using the `:as` option in our routes. Either way, thanks a lot for looking into this!

---Sdcrouse

**Comment by HopperMCS** [comment]
Sorry to bump this, but I agree. If a CL or whoever does these reads this, dear god please remove it. I'm stuck on this lab and am very tempted to just comment out that part of the spec file. Learn's documentation for this can't be described as egregious simply due to the fact that it doesn't exist in the first place.

**Comment by Sdcrouse** [comment]
@MGageMorgan Sorry to hear that you've been stuck on that lab!

It looks like redirecting is covered in the **Create Action** lesson: https://learn.co/tracks/full-stack-web-development-v8/module-13-rails/section-5-crud-with-rails/create-action

That should help you pass the test.

**Comment by Sdcrouse** [comment]
Fair warning, though: It looks like I raised an issue on that lesson, too; the redirect part is correct, but part of the lesson is out of date.

**Comment by HopperMCS** [comment]
I disabled the tests. The redirect_to was covered after this lesson. I feel this test serves no actual purpose and you can get by just fine without actually doing it.

**Comment by Sdcrouse** [comment]
Good to know!
