### ISSUE TITLE
Issues with secrets.yml

### ISSUE THREAD

**Issue by seemajune** [learn-co-curriculum/rails-url-helpers-lab#3]
Students have been receiving error upon opening this lab, that they didn't set their secret token in the secrets.yml file: 

DEPRECATION WARNING: You didn't set secret_key_base. Read the upgrade documentation to learn more about this new config option. (called from get at /Users/<THEIR USER NAME>/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/forwardable.rb:183)
has an index page (FAILED - 1)

Multiple students
DEPRECATION WARNING: You didn't set `secret_key_base`. Read the upgrade documentation to learn more about this new config option. (called from get at /Users/<THEIR USER NAME>/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/forwardable.rb:183)
shows them on the index page

Students have been googling and creating their own secrets.yml file, setting the secret token to resolve the issue.

**Comment by dannyd4315** [comment]
This is still an issue. There is a secrets.yml file with secret_key_base values in, however it still shows the error?

**Comment by aviflombaum** [comment]
The secrets.yml file seems to be missing. Adding one should fix this.

**Comment by pletcher** [comment]
Fixed in https://github.com/learn-co-curriculum/rails-url-helpers-lab/commit/ebe8190048a97548dd90167e7e66de2b025d7e2b
