### ISSUE TITLE
.active method doesn't work and requires a funky fix

### ISSUE THREAD

**Issue by febbraiod** [learn-co-curriculum/rails-url-helpers-lab#6]
<img width="653" alt="screen shot 2016-02-13 at 2 23 07 pm" src="https://cloud.githubusercontent.com/assets/15745614/13029568/de2c3d5a-d25d-11e5-80d2-06f80f528102.png">

**Comment by AnnJohn** [comment]
thanks for raising this issue.  if possible, can you clarify what happened without the fix?

**Comment by jmburges** [comment]
Hey @febbraiod this is a feature not a bug! haha

It requires you to create a default value for a column. What you did works (I'd probably rename the method :smile: ) but you can also just do it in a rails migration: https://stackoverflow.com/questions/1186400/correct-way-to-set-default-values-in-rails.

Let's just add something to this readme that explains that the student should google how to set a default value for something
